# Generated by Django 4.2.3 on 2023-07-10 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название записи')),
                ('description', models.TextField(verbose_name='Описание записи')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 7, 10, 14, 47, 47, 202336), verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='image/%Y', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('text', models.TextField(max_length=250, verbose_name='Текст комментария')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.addnewpost', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
