# Generated by Django 4.2.3 on 2023-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_addcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='text',
            field=models.TextField(max_length=250, verbose_name='Текст комментария'),
        ),
    ]
