# Generated by Django 4.2.3 on 2023-07-10 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 15, 15, 15, 286420), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='addnewpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
