# Generated by Django 4.2.3 on 2023-07-19 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_addnewpost_date_created_alter_addnewpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 12, 40, 18, 27908), verbose_name='Дата публикации'),
        ),
    ]
